src/EventHorizon/RpgBundle/Entity/Journal.php
<?php

namespace EventHorizon\RpgBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * EventHorizon\RpgBundle\Entity\Journal
 *
 * @ORM\Table(
 *   name="journal",
 *   indexes={
 *     @ORM\Index(name="journal_main_01_index", columns={"id", "character_id", "quest_id", "user_id", "is_completed", "is_hidden", "is_ordered_by_someone_else", "is_visible", "completed_at", "created_at", "updated_at"}),
 *     @ORM\Index(name="journal_01_index", columns={"publish_on_facebook"}),
 *     @ORM\Index(name="journal_02_index", columns={"journal_id", "completed_quest_counter", "quest_counter"})
 *   })
 * @ORM\Entity(repositoryClass="EventHorizon\RpgBundle\Repository\JournalRepository")
 */
class Journal
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var integer $character_id
     *
     * @Assert\Type(type="EventHorizon\RpgBundle\Entity\Character")
     * @ORM\ManyToOne(cascade={"remove"}, inversedBy="journal", targetEntity="EventHorizon\RpgBundle\Entity\Character")
     * @ORM\JoinColumn(name="character_id", nullable=false, onDelete="CASCADE", referencedColumnName="id")
     */
    protected $character;

    /**
     * @var integer $journal_id
     *
     * @Assert\Type(type="EventHorizon\RpgBundle\Entity\Journal")
     * @ORM\ManyToOne(cascade={"remove"}, inversedBy="subquest", targetEntity="EventHorizon\RpgBundle\Entity\Journal")
     * @ORM\JoinColumn(name="journal_id", nullable=true, onDelete="CASCADE", referencedColumnName="id")
     */
    protected $journal;

    /**
     * @var integer $quest_id
     *
     * @Assert\Type(type="EventHorizon\RpgBundle\Entity\Quest")
     * @ORM\ManyToOne(cascade={"remove"}, inversedBy="journal", targetEntity="EventHorizon\RpgBundle\Entity\Quest")
     * @ORM\JoinColumn(name="quest_id", nullable=false, onDelete="CASCADE", referencedColumnName="id")
     */
    protected $quest;

    /**
     * @ORM\OneToMany(targetEntity="EventHorizon\RpgBundle\Entity\Journal", mappedBy="journal")
     */
    protected $subquest;

    /**
     * @var integer $user_id
     *
     * @Assert\Type(type="EventHorizon\RpgBundle\Entity\User")
     * @ORM\ManyToOne(cascade={"remove"}, inversedBy="journal", targetEntity="EventHorizon\RpgBundle\Entity\User")
     * @ORM\JoinColumn(name="user_id", nullable=false, onDelete="CASCADE", referencedColumnName="id")
     */
    protected $user;

    /**
     * @var integer $is_completed
     *
     * @ORM\Column(name="is_completed", type="integer")
     */
    private $is_completed = 0;

    /**
     * @var integer $is_hidden
     *
     * @ORM\Column(name="is_hidden", type="integer")
     */
    private $is_hidden = 0;

    /**
     * @var integer $is_ordered_by_someone_else
     *
     * @ORM\Column(name="is_ordered_by_someone_else", type="integer")
     */
    private $is_ordered_by_someone_else = 0;

    /**
     * @var integer $is_visible
     *
     * @ORM\Column(name="is_visible", type="integer")
     */
    private $is_visible = 0;

    /**
     * @var integer $publish_on_facebook
     *
     * @ORM\Column(name="publish_on_facebook", type="integer")
     */
    private $publish_on_facebook = 0;

    /**
     * @var integer $completed_quest_counter
     *
     * @ORM\Column(name="completed_quest_counter", type="integer")
     */
    private $completed_quest_counter = 0;

    /**
     * @var integer $quest_counter
     *
     * @ORM\Column(name="quest_counter", type="integer")
     */
    private $quest_counter = 0;

    /**
     * @var datetime $completed_at
     *
     * @ORM\Column(name="completed_at", nullable=true, type="datetime")
     */
    private $completed_at;

    /**
     * @var datetime $created_at
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $created_at;

    /**
     * @var datetime $updated_at
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->subquest = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->id;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get character_id
     *
     * @return integer
     */
    public function getCharacterId()
    {
        return $this->character_id;
    }

    /**
     * Set character
     *
     * @param object $character
     */
    public function setCharacter(Character $character)
    {
        $this->character = $character;
    }

    /**
     * Set character_id
     *
     * @param integer $character_id
     */
    public function setCharacterId($character_id)
    {
        $this->character_id = $character_id;
    }

    /**
     * Get journal
     *
     * @return object
     */
    public function getJournal()
    {
        return $this->journal;
    }

    /**
     * Set journal
     *
     * @param object $journal
     */
    public function setJournal(Journal $journal)
    {
        $this->journal = $journal;
    }

    /**
     * Get quest
     *
     * @return object
     */
    public function getQuest()
    {
        return $this->quest;
    }

    /**
     * Get quest_id
     *
     * @return integer
     */
    public function getQuestId()
    {
        return $this->quest_id;
    }

    /**
     * Set quest
     *
     * @param object $quest
     */
    public function setQuest(Quest $quest)
    {
        $this->quest = $quest;
    }

    /**
     * Set quest_id
     *
     * @param integer $quest_id
     */
    public function setQuestId($quest_id)
    {
        $this->quest_id = $quest_id;
    }

    /**
     * Get subquest
     *
     * @return object
     */
    public function getSubquest()
    {
        return $this->subquest;
    }

    /**
     * Set subquest
     *
     * @param object $subquest
     */
    public function setSubquest(Journal $subquest)
    {
        $this->subquest = $subquest;
    }

    /**
     * Get user
     *
     * @return object
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Get user_id
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Set user
     *
     * @param object $user
     */
    public function setUser(User $user)
    {
        $this->user = $user;
    }

    /**
     * Set user_id
     *
     * @param integer $user_id
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;
    }

    /**
     * Get is_completed
     *
     * @return integer
     */
    public function getIsCompleted()
    {
        return $this->is_completed;
    }

    /**
     * Set is_completed
     *
     * @param integer $is_completed
     */
    public function setIsCompleted($is_completed)
    {
        $this->is_completed = $is_completed;
    }

    /**
     * Get is_hidden
     *
     * @return integer
     */
    public function getIsHidden()
    {
        return $this->is_hidden;
    }

    /**
     * Set is_hidden
     *
     * @param integer $is_hidden
     */
    public function setIsHidden($is_hidden)
    {
        $this->is_hidden = $is_hidden;
    }

    /**
     * Get is_ordered_by_someone_else
     *
     * @return integer
     */
    public function getIsOrderedBySomeoneElse()
    {
        return $this->is_ordered_by_someone_else;
    }

    /**
     * Set is_ordered_by_someone_else
     *
     * @param integer $is_ordered_by_someone_else
     */
    public function setIsOrderedBySomeoneElse($is_ordered_by_someone_else)
    {
        $this->is_ordered_by_someone_else = $is_ordered_by_someone_else;
    }

    /**
     * Get is_visible
     *
     * @return integer
     */
    public function getIsVisible()
    {
        return $this->is_visible;
    }

    /**
     * Set is_visible
     *
     * @param integer $is_visible
     */
    public function setIsVisible($is_visible)
    {
        $this->is_visible = $is_visible;
    }

    /**
     * Get publish_on_facebook
     *
     * @return integer
     */
    public function getPublishOnFacebook()
    {
        return $this->publish_on_facebook;
    }

    /**
     * Set publish_on_facebook
     *
     * @param integer $publish_on_facebook
     */
    public function setPublishOnFacebook($publish_on_facebook)
    {
        $this->publish_on_facebook = $publish_on_facebook;
    }

    /**
     * Get completed_quest_counter
     *
     * @return integer
     */
    public function getCompletedQuestCounter()
    {
        return $this->completed_quest_counter;
    }

    /**
     * Set completed_quest_counter
     *
     * @param integer $completed_quest_counter
     */
    public function setCompletedQuestCounter($completed_quest_counter)
    {
        $this->completed_quest_counter = $completed_quest_counter;
    }

    /**
     * Get quest_counter
     *
     * @return integer
     */
    public function getQuestCounter()
    {
        return $this->quest_counter;
    }

    /**
     * Set quest_counter
     *
     * @param integer $quest_counter
     */
    public function setQuestCounter($quest_counter)
    {
        $this->quest_counter = $quest_counter;
    }

    /**
     * Get completed_at
     *
     * @return datetime
     */
    public function getCompletedAt()
    {
        return $this->completed_at;
    }

    /**
     * Set completed_at
     *
     * @param datetime $completedAt
     */
    public function setCompletedAt($completedAt)
    {
        $this->completed_at = $completedAt;
    }

    /**
     * Get created_at
     *
     * @return datetime
     */
    public function getCreatedAt()
    {

src/EventHorizon/RpgBundle/Entity/Quest.php
<?php

namespace EventHorizon\RpgBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * EventHorizon\RpgBundle\Entity\Quest
 *
 * @ORM\Table(
 *   name="quest",
 *   indexes={
 *     @ORM\Index(name="quest_main_01_index", columns={"id", "character_id", "user_id", "attribute_reward", "skill_reward", "is_blocked", "is_group_quest", "created_at", "updated_at"}),
 *     @ORM\Index(name="quest_01_index", columns={"type"})
 *   })
 * @ORM\Entity(repositoryClass="EventHorizon\RpgBundle\Repository\QuestRepository")
 */
class Quest
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var integer $character_id
     *
     * @Assert\Type(type="EventHorizon\RpgBundle\Entity\Character")
     * @ORM\ManyToOne(cascade={"remove"}, inversedBy="quest", targetEntity="EventHorizon\RpgBundle\Entity\Character")
     * @ORM\JoinColumn(name="character_id", nullable=false, onDelete="CASCADE", referencedColumnName="id")
     */
    protected $character;

    /**
     * @ORM\OneToMany(targetEntity="EventHorizon\RpgBundle\Entity\Journal", mappedBy="quest")
     */
    protected $journal;

    /**
     * @var integer $user_id
     *
     * @Assert\Type(type="EventHorizon\RpgBundle\Entity\User")
     * @ORM\ManyToOne(cascade={"remove"}, inversedBy="quest", targetEntity="EventHorizon\RpgBundle\Entity\User")
     * @ORM\JoinColumn(name="user_id", nullable=false, onDelete="CASCADE", referencedColumnName="id")
     */
    protected $user;

    /**
     * @var string $attribute_reward
     *
     * @Assert\NotBlank()
     * @ORM\Column(name="attribute_reward", type="string", length=255)
     */
    private $attribute_reward;

    /**
     * @var string $content
     *
     * @Assert\MaxLength(16384)
     * @Assert\NotBlank()
     * @ORM\Column(name="content", type="text")
     */
    private $content;

    /**
     * @var string $skill_reward
     *
     * @Assert\NotBlank()
     * @ORM\Column(name="skill_reward", type="string", length=255)
     */
    private $skill_reward;

    /**
     * @var string $title
     *
     * @Assert\MaxLength(250)
     * @Assert\NotBlank()
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var string $type
     *
     * @Assert\MaxLength(250)
     * @Assert\NotBlank()
     * @ORM\Column(name="type", type="string", length=255)
     */
    private $type;

    /**
     * @var integer $is_blocked
     *
     * @ORM\Column(name="is_blocked", type="integer")
     */
    private $is_blocked = 0;

    /**
     * @var integer $is_group_quest
     *
     * @ORM\Column(name="is_group_quest", type="integer")
     */
    private $is_group_quest = 0;

    /**
     * @var datetime $created_at
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $created_at;

    /**
     * @var datetime $updated_at
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->journal = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get character_id
     *
     * @return integer
     */
    public function getCharacterId()
    {
        return $this->character_id;
    }

    /**
     * Set character
     *
     * @param object $character
     */
    public function setCharacter(Character $character)
    {
        $this->character = $character;
    }

    /**
     * Set character_id
     *
     * @param integer $character_id
     */
    public function setCharacterId($character_id)
    {
        $this->character_id = $character_id;
    }

    /**
     * Get journal
     *
     * @return integer
     */
    public function getJournal()
    {
        return $this->journal;
    }

    /**
     * Get user
     *
     * @return integer
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Get user_id
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Set user
     *
     * @param object $user
     */
    public function setUser(User $user)
    {
        $this->user = $user;
    }

    /**
     * Set user_id
     *
     * @param integer $user_id
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;
    }

    /**
     * Get attribute_reward
     *
     * @return string
     */
    public function getAttributeReward()
    {
        return $this->attribute_reward;
    }

    /**
     * Set attribute_reward
     *
     * @param string $attributeReward
     */
    public function setAttributeReward($attributeReward)
    {
        $this->attribute_reward = $attributeReward;
    }

    /**
     * Get content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set content
     *
     * @param string $content
     */
    public function setContent($content)
    {
        $this->content = $content;
    }

    /**
     * Get skill_reward
     *
     * @return string
     */
    public function getSkillReward()
    {
        return $this->skill_reward;
    }

    /**
     * Set skill_reward
     *
     * @param string $skillReward
     */
    public function setSkillReward($skillReward)
    {
        $this->skill_reward = $skillReward;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set title
     *
     * @param string $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * Get type
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set type
     *
     * @param string $type
     */
    public function setType($type)
    {
        $this->type = $type;
    }

    /**
     * Get is_blocked
     *
     * @return integer
     */
    public function getIsBlocked()
    {
        return $this->is_blocked;
    }

    /**
     * Set is_blocked
     *
     * @param integer $is_blocked
     */
    public function setIsBlocked($is_blocked)
    {
        $this->is_blocked = $is_blocked;
    }

    /**
     * Get is_group_quest
     *
     * @return integer
     */
    public function getIsGroupQuest()
    {
        return $this->is_group_quest;
    }

    /**
     * Set is_group_quest
     *
     * @param integer $is_group_quest
     */
    public function setIsGroupQuest($is_group_quest)
    {
        $this->is_group_quest = $is_group_quest;
    }

    /**
     * Get created_at
     *
     * @return datetime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set created_at
     *
     * @param datetime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;
    }

    /**
     * Get updated_at
     *
     * @return datetime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Set updated_at
     *
     * @param datetime $updatedAt
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;
    }

    public function __toString()
    {
        return $this->id;
    }
}

src/EventHorizon/RpgBundle/Resources/views/Journal/JournalShow.html.twig
{% extends 'EventHorizonRpgBundle::layout.html.twig' %}

{% block title %}
    {{ setup.gameName }} - {% filter lower %}{% trans %}Zadanie{% endtrans %}{% endfilter %} - {{ journal.quest.title }}
{% endblock %}

{% block breadcrumb %}
    {% if journal.isCompleted == 0 %}
        <li><span class="divider">/</span> <a href="{{ path('journal', { 'mode': 'todo' }) }}">{% trans %}Zadania{% endtrans %} - {% filter lower %}{% trans %}Do wykonania{% endtrans %}{% endfilter %}</a></li>
    {% elseif journal.isCompleted == 1 %}
        <li><span class="divider">/</span> <a href="{{ path('journal', { 'mode': 'done' }) }}">{% trans %}Zadania{% endtrans %} - {% filter lower %}{% trans %}Wykonane{% endtrans %}{% endfilter %}</a></li>
    {% endif %}
    <li><span class="divider">/</span> <a href="{{ path('journal_show', { 'id': journal.id }) }}">{% trans %}Zadanie{% endtrans %}</a></li>
{% endblock %}

{% block content %}
    {% include 'EventHorizonRpgBundle:Journal:Show.html.twig' with { 'access_mode': 'admin', 'display_mode': 'show' } %}
{% endblock %}

src/EventHorizon/RpgBundle/Resources/views/Journal/Show.html.twig
{% if display_mode == 'show' %}
    <div class="span8 offset2 well">
        <a class="btn btn-info btn-small vertical_align_top" data-content="{% trans %}W tym oknie wyświetlane jest zadanie użytkownika.<br /><br />Użytkownik wyznacza sobie kolejne cele (zadania). Realizując je zmienia i kształtuje swoje życie.{% endtrans %}" data-original-title="{% trans %}Zadanie{% endtrans %}" data-trigger="hover" href="#" rel="popover"><i class="icon-question-sign icon-white"></i></a>
        <div class="page-header">
            <h3>{{ journal.quest.title }}</h3>
        </div>
{% endif %}

<div class="span7">
    {% if display_mode == 'list' %}
        <div class="page-header"></div>
        <h3>
            {% if access_mode == 'admin' %}
                <a href="{{ path('journal_show', { 'id': journal.id }) }}">{{ journal.quest.title|truncate(64) }}</a>
            {% elseif access_mode == 'visitor' %}
                <a href="{{ path('show_journal', { 'journal_id': journal.id, 'user_id': journal.user.id }) }}">{{ journal.quest.title|truncate(64) }}</a>
            {% endif %}
        </h3>
        <p>{{ journal.quest.content|truncate(256) }}</p>
    {% elseif display_mode == 'show' %}
        <p>{{ journal.quest.content }}</p>
    {% endif %}
    {% if journal.journal %}
        {% trans %}Zadanie nadrzędne{% endtrans %}:
        <ul>
            {% if access_mode == 'admin' %}
                <li>
                    <a href="{{ path('journal_show', { 'id': journal.journal.id }) }}">{{ journal.journal.quest.title|truncate(64) }}</a>
                </li>
            {% elseif access_mode == 'visitor' %}
                {% if journal.journal.isVisible %}
                    <li>
                        <a href="{{ path('show_journal', { 'journal_id': journal.journal.id, 'user_id': journal.journal.user.id }) }}">{{ journal.journal.quest.title|truncate(64) }}</a>
                    </li>
                {% endif %}
            {% endif %}
        </ul>
    {% endif %}
    {% if ((journal.quest.type == "dream") or (journal.quest.type == "training")) %}
        {% if journal.questCounter %}
            <div title="{{ journal.completedQuestCounter }} / {{ journal.questCounter }}" rel="tooltip">
                <div class="progress"><div class="bar" style="width: {{ ((journal.completedQuestCounter / journal.questCounter) * 100) }}%;"></div></div>
            </div>
            {% trans %}Podzadania{% endtrans %}:
            <ul>
                {% for subquest in journal.subQuest if (subquest.isHidden == 0) %}
                    {% if access_mode == 'admin' %}
                        <li class="padding_bottom_05em">
                            {% include 'EventHorizonRpgBundle:Journal:SidequestInfo.html.twig' %}
                            <a href="{{ path('journal_show', { 'id': subquest.id }) }}">{{ subquest.quest.title|truncate(64) }}</a>
                        </li>
                    {% elseif access_mode == 'visitor' %}
                        {% if subquest.isVisible %}
                            <li class="padding_bottom_05em">
                                {% include 'EventHorizonRpgBundle:Journal:SidequestInfo.html.twig' %}
                                <a href="{{ path('show_journal', { 'journal_id': subquest.id, 'user_id': subquest.user.id }) }}">{{ subquest.quest.title|truncate(64) }}</a>
                            </li>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
    {% endif %}
    <p class="font_size_11px font_weight_bold muted text_transform_uppercase">
        {% trans %}Wzrost cechy{% endtrans %}: {{ journal.quest.attributeReward|trans }}<br />
        {% trans %}Wzrost współczynnika{% endtrans %}: {{ journal.quest.skillReward|trans }}<br />
        {% trans %}Typ zadania{% endtrans %}: {{ journal.quest.type|trans }}
    </p>
    <div class="btn-toolbar">
        {% if journal.isCompleted == 0 %}
            {% if access_mode == 'admin' %}
                <div class="btn-group">
                    <a class="btn btn-success btn-mini complete_quest" data-confirm-cancel="{% trans %}Anuluj{% endtrans %}" data-confirm-direction="ltr" data-confirm-message="{% trans %}Czy na pewno chcesz zakończyć zadanie?{% endtrans %}" data-confirm-ok="{% trans %}Tak{% endtrans %}" data-confirm-title="{% trans %}Potwierdzenie{% endtrans %}" href="{{ path('journal_complete', { 'id': journal.id }) }}"><i class="icon-ok icon-white vertical_align_middle"></i> {% trans %}Zakończenie zadania{% endtrans %}</a>
                </div>

                <div class="btn-group">
                    <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="icon-cog vertical_align_middle"></i> {% trans %}Opcje{% endtrans %}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        {% if journal.quest.isGroupQuest == 0 %}
                            <li><a href="{{ path('quest_edit', { 'id': journal.quest.id }) }}"><i class="icon-edit"></i> {% trans %}Edycja zadania{% endtrans %}</a></li>
                        {% endif %}
                        <li><a class="hide_quest" data-confirm-cancel="{% trans %}Anuluj{% endtrans %}" data-confirm-direction="ltr" data-confirm-message="{% trans %}Czy na pewno chcesz ukryć zadanie?{% endtrans %}" data-confirm-ok="{% trans %}Tak{% endtrans %}" data-confirm-title="{% trans %}Potwierdzenie{% endtrans %}" href="{{ path('journal_hide', { 'id': journal.id }) }}"><i class="icon-eye-close"></i> {% trans %}Ukryj zadanie{% endtrans %}</a></li>
                    </ul>
                </div>
                {% if ((journal.quest.type == "dream") or (journal.quest.type == "training")) %}
                    <div class="btn-group">
                        <a class="btn btn-primary btn-mini" href="{{ path('quest_new', { journal_id: journal.id }) }}"><i class="icon-pencil icon-white"></i> {% trans %}Nowe podzadanie{% endtrans %}</a>
                    </div>
                {% endif %}
            {% endif %}
        {% endif %}
        {% if display_mode == 'show' %}
            <div class="btn-group">
                {% if access_mode == 'admin' %}
                    {% if journal.isCompleted == 0 %}
                        <a class="btn btn-mini" href="{{ path('journal', { 'mode': 'todo' }) }}"><i class="icon-arrow-left vertical_align_middle"></i> {% trans %}Powrót{% endtrans %}</a>
                    {% elseif journal.isCompleted == 1 %}
                        <a class="btn btn-mini" href="{{ path('journal', { 'mode': 'done' }) }}"><i class="icon-arrow-left vertical_align_middle"></i> {% trans %}Powrót{% endtrans %}</a>
                    {% endif %}
                {% elseif access_mode == 'visitor' %}
                    {% if journal.isCompleted == 0 %}
                        <a class="btn btn-mini" href="{{ path('show_journals', { 'user_id': journal.user.id, 'mode': 'todo' }) }}"><i class="icon-arrow-left vertical_align_middle"></i> {% trans %}Powrót{% endtrans %}</a>
                    {% elseif journal.isCompleted == 1 %}
                        <a class="btn btn-mini" href="{{ path('show_journals', { 'user_id': journal.user.id, 'mode': 'done' }) }}"><i class="icon-arrow-left vertical_align_middle"></i> {% trans %}Powrót{% endtrans %}</a>
                    {% endif %}
                {% endif %}
            </div>
        {% endif %}
    </div>
</div>
{% if display_mode == 'show' %}
    </div>
{% endif %}

src/EventHorizon/RpgBundle/Resources/views/Journal/SidequestInfo.html.twig
{% if subquest.isCompleted == 0 %}
    <span class="label label-info l1-label" title="{% trans %}Zadanie czeka na wykonanie{% endtrans %}"><i class="icon-road icon-white"></i></span>
{% elseif subquest.isCompleted == 1 %}
    <span class="label label-success l1-label" title="{% trans %}Zadanie zostało zakończone{% endtrans %}"><i class="icon-thumbs-up icon-white"></i></span>
{% endif %}
{% if subquest.quest.type == "standard" %}
    <span class="label l1-label" title="{% trans %}Standardowe{% endtrans %}">S</span>
{% elseif subquest.quest.type == "dream" %}
    <span class="label label-warning l1-label" title="{% trans %}Marzenie{% endtrans %}">D</span>
{% elseif subquest.quest.type == "training" %}
    <span class="label label-important l1-label" title="{% trans %}Trening{% endtrans %}">T</span>
{% endif %}