src/EventHorizon/RpgBundle/Entity/Reward.php
<?php

namespace EventHorizon\RpgBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * EventHorizon\RpgBundle\Entity\Reward
 *
 * @ORM\Table(
 *   name="reward",
 *   indexes={
 *     @ORM\Index(name="reward_main_01_index", columns={"id", "character_id", "user_id", "level", "is_awarded", "is_blocked", "is_visible", "awarded_at", "created_at", "updated_at"}),
 *     @ORM\Index(name="reward_01_index", columns={"is_received"})
 *   })
 * @ORM\Entity(repositoryClass="EventHorizon\RpgBundle\Repository\RewardRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Reward
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var integer $character_id
     *
     * @Assert\Type(type="EventHorizon\RpgBundle\Entity\Character")
     * @ORM\ManyToOne(cascade={"remove"}, inversedBy="reward", targetEntity="EventHorizon\RpgBundle\Entity\Character")
     * @ORM\JoinColumn(name="character_id", nullable=false, onDelete="CASCADE", referencedColumnName="id")
     */
    protected $character;

    /**
     * @var integer $user_id
     *
     * @Assert\Type(type="EventHorizon\RpgBundle\Entity\User")
     * @ORM\ManyToOne(cascade={"remove"}, inversedBy="reward", targetEntity="EventHorizon\RpgBundle\Entity\User")
     * @ORM\JoinColumn(name="user_id", nullable=false, onDelete="CASCADE", referencedColumnName="id")
     */
    protected $user;

    /**
     * @var string $content
     *
     * @Assert\MaxLength(16384)
     * @Assert\NotBlank()
     * @ORM\Column(name="content", type="text")
     */
    private $content;

    /**
     * @var integer $level
     *
     * @ORM\Column(name="level", type="integer")
     */
    private $level = 0;

    /**
     * @var string $photo
     *
     * @ORM\Column(length=255, name="photo", nullable=true, type="string")
     */
    private $photo;

    /**
     * @Assert\File(
     *     maxSize="256k",
     *     mimeTypes={"image/png", "image/jpeg", "image/pjpeg"}
     * )
     */
    private $photo_file;

    /**
     * @var string $title
     *
     * @Assert\MaxLength(250)
     * @Assert\NotBlank()
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var integer $is_awarded
     *
     * @ORM\Column(name="is_awarded", type="integer")
     */
    private $is_awarded = 0;

    /**
     * @var integer $is_blocked
     *
     * @ORM\Column(name="is_blocked", type="integer")
     */
    private $is_blocked = 0;

    /**
     * @var integer $is_received
     *
     * @ORM\Column(name="is_received", type="integer")
     */
    private $is_received = 0;

    /**
     * @var integer $is_visible
     *
     * @ORM\Column(name="is_visible", type="integer")
     */
    private $is_visible = 0;

    /**
     * @var datetime $awarded_at
     *
     * @ORM\Column(name="awarded_at", nullable=true, type="datetime")
     */
    private $awarded_at;

    /**
     * @var datetime $created_at
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $created_at;

    /**
     * @var datetime $updated_at
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updated_at;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get character_id
     *
     * @return integer
     */
    public function getCharacterId()
    {
        return $this->character_id;
    }

    /**
     * Set character
     *
     * @param object $character
     */
    public function setCharacter(Character $character)
    {
        $this->character = $character;
    }

    /**
     * Set character_id
     *
     * @param integer $character_id
     */
    public function setCharacterId($character_id)
    {
        $this->character_id = $character_id;
    }

    /**
     * Get user
     *
     * @return integer
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Get user_id
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Set user
     *
     * @param object $user
     */
    public function setUser(User $user)
    {
        $this->user = $user;
    }

    /**
     * Set user_id
     *
     * @param integer $user_id
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;
    }

    /**
     * Get content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set content
     *
     * @param string $content
     */
    public function setContent($content)
    {
        $this->content = $content;
    }

    /**
     * Get level
     *
     * @return string
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Set level
     *
     * @param string $level
     */
    public function setLevel($level)
    {
        $this->level = $level;
    }

    /**
     * Get photo
     *
     * @return string
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * Set photo
     *
     * @param string $photo
     */
    public function setPhoto($photo)
    {
        $this->photo = $photo;
    }

    /**
     * Get photo_file
     */
    public function getPhotoFile()
    {
        return $this->photo_file;
    }

    /**
     * Set photo_file
     */
    public function setPhotoFile($photo_file)
    {
        $this->photo_file = $photo_file;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set title
     *
     * @param string $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * Get is_awarded
     *
     * @return integer
     */
    public function getIsAwarded()
    {
        return $this->is_awarded;
    }

    /**
     * Set is_awarded
     *
     * @param integer $is_awarded
     */
    public function setIsAwarded($is_awarded)
    {
        $this->is_awarded = $is_awarded;
    }

    /**
     * Get is_blocked
     *
     * @return integer
     */
    public function getIsBlocked()
    {
        return $this->is_blocked;
    }

    /**
     * Set is_blocked
     *
     * @param integer $is_blocked
     */
    public function setIsBlocked($is_blocked)
    {
        $this->is_blocked = $is_blocked;
    }

    /**
     * Get is_received
     *
     * @return integer
     */
    public function getIsReceived()
    {
        return $this->is_received;
    }

    /**
     * Set is_received
     *
     * @param integer $is_received
     */
    public function setIsReceived($is_received)
    {
        $this->is_received = $is_received;
    }

    /**
     * Get is_visible
     *
     * @return integer
     */
    public function getIsVisible()
    {
        return $this->is_visible;
    }

    /**
     * Set is_visible
     *
     * @param integer $is_visible
     */
    public function setIsVisible($is_visible)
    {
        $this->is_visible = $is_visible;
    }

    /**
     * Get awarded_at
     *
     * @return datetime
     */
    public function getAwardedAt()
    {
        return $this->awarded_at;
    }

    /**
     * Set awarded_at
     *
     * @param datetime $awarded_at
     */
    public function setAwardedAt($awarded_at)
    {
        $this->awarded_at = $awarded_at;
    }

    /**
     * Get created_at
     *
     * @return datetime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set created_at
     *
     * @param datetime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;
    }

    /**
     * Get updated_at
     *
     * @return datetime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Set updated_at
     *
     * @param datetime $updatedAt
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;
    }

    public function getAbsolutePath()
    {
        return null === $this->photo ? null : $this->getUploadRootDir().'/'.$this->photo;
    }

    public function checkAbsolutePath()
    {
        $path = $this->getAbsolutePath();

        if ($path) {
            if (is_readable($path)) {
                return true;
            }
        }

        return false;
    }

    protected function getUploadDir()
    {
        return 'uploads/rewards';
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    public function getWebPath()
    {
        return null === $this->photo ? null : $this->getUploadDir().'/'.$this->photo;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if (null !== $this->photo_file) {
            $this->photo = uniqid().'.'.$this->photo_file->guessExtension();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if (null === $this->photo_file) {
            return;
        }

        $this->photo_file->move($this->getUploadRootDir(), $this->photo);

        unset($this->photo_file);
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if ($photo_file = $this->getAbsolutePath()) {
            unlink($photo_file);
        }
    }
}

src/EventHorizon/RpgBundle/Controller/RewardController.php
<?php

namespace EventHorizon\RpgBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use EventHorizon\RpgBundle\EventHorizonRpgBundle;
use EventHorizon\RpgBundle\Entity\Reward;
use EventHorizon\RpgBundle\Form\RewardType;

class RewardController extends Controller
{
    public function common()
    {
        $this->em = $this->getDoctrine()->getManager();
        $this->setup = $this->em->getRepository('EventHorizonRpgBundle:Setup')->getSetup();
        $this->user = $this->container->get('security.context')->getToken()->getUser();
        $this->user_id = $this->user->getId();
        $this->request = $this->getRequest();
        $this->request->setLocale($this->get('session')->get('_locale'));
        $this->request->getSession()->set('referrer', $this->request->getRequestUri());
    }

    public function indexAction()
    {
        $this->common();
        $rewards = $this->em->getRepository('EventHorizonRpgBundle:Reward')->getRewardsByUserIdV1($this->user_id);
        $character = $this->em->getRepository('EventHorizonRpgBundle:Character')->getCharacterByUserIdV2($this->user_id);
        $level = ($character->getLevel() + 1);
        $reward = $this->em->getRepository('EventHorizonRpgBundle:Reward')->getRewardsByUserIdAndLevelV1($this->user_id, $level);

        if ($reward) {
            $new_reward = 0;
        } else {
            $new_reward = 1;
        }

        return $this->render('EventHorizonRpgBundle:Reward:RewardsList.html.twig', array(
            'level'      => $level,
            'new_reward' => $new_reward,
            'rewards'    => $rewards,
            'setup'      => $this->setup,
        ));
    }

    public function NewCommon()
    {
        $this->common();
        $this->character = $this->em->getRepository('EventHorizonRpgBundle:Character')->getCharacterByUserIdV2($this->user_id);
        $this->level = ($this->character->getLevel() + 1);
        $this->rewardExists = $this->em->getRepository('EventHorizonRpgBundle:Reward')->getRewardsByUserIdAndLevelV1($this->user_id, $this->level);

        $this->reward = new Reward();
        $this->form = $this->createForm(new RewardType(array('user' => $this->user)), $this->reward);
    }

    public function newAction()
    {
        $this->NewCommon();

        if ($this->rewardExists) {
            $this->get('session')->setFlash('info', $this->get('translator')->trans('Masz już wybraną nagrodę za osiągnięcie poziomu'));

            return $this->redirect($this->generateUrl('reward'));
        }

        return $this->render('EventHorizonRpgBundle:Reward:New.html.twig', array(
            'form'   => $this->form->createView(),
            'reward' => $this->reward,
            'setup'  => $this->setup,
        ));
    }

    public function createAction()
    {
        $this->NewCommon();

        if ($this->rewardExists) {
            $this->get('session')->setFlash('info', $this->get('translator')->trans('Masz już wybraną nagrodę za osiągnięcie poziomu'));

            return $this->redirect($this->generateUrl('reward'));
        }

        $this->form->bind($this->request);

        if ($this->form->isValid()) {
            $this->em->getRepository('EventHorizonRpgBundle:Reward')->saveNewReward($this->reward, $this->user);

            return $this->redirect($this->generateUrl('reward'));
        }

        return $this->render('EventHorizonRpgBundle:Reward:New.html.twig', array(
            'form'   => $this->form->createView(),
            'reward' => $this->reward,
            'setup'  => $this->setup,
        ));
    }

    public function EditCommon($id)
    {
        $this->common();
        $is_awarded = 0;

        $this->reward = $this->em->getRepository('EventHorizonRpgBundle:Reward')->getRewardByIdAndUserIdAndIsAwardedV1($id, $this->user_id, $is_awarded);

        if (!($this->reward)) {
            $this->message = "EventHorizonRpgBundle:Reward:EditCommon id=".$id." user_id=".$this->user_id." is_awarded=".$is_awarded;
            EventHorizonRpgBundle::addNotice($this->message, $this->get('event_horizon_log'), $this->get('request'));

            throw $this->createNotFoundException('Unable to find Reward entity.');
        }

        $this->form = $this->createForm(new RewardType(), $this->reward);
    }

    public function editAction($id)
    {
        $this->EditCommon($id);

        return $this->render('EventHorizonRpgBundle:Reward:Edit.html.twig', array(
            'form'   => $this->form->createView(),
            'reward' => $this->reward,
            'setup'  => $this->setup,
        ));
    }

    public function updateAction($id)
    {
        $this->EditCommon($id);

        $this->form->bind($this->request);

        if ($this->form->isValid()) {
            $this->em->getRepository('EventHorizonRpgBundle:Reward')->saveEditReward($this->reward, $this->user);

            return $this->redirect($this->generateUrl('reward'));
        }

        return $this->render('EventHorizonRpgBundle:Reward:Edit.html.twig', array(
            'form'   => $this->form->createView(),
            'reward' => $this->reward,
            'setup'  => $this->setup,
        ));
    }

    public function receiveAction($id)
    {
        $this->common();
        $is_awarded = 1;
        $is_received = 0;

        $reward = $this->em->getRepository('EventHorizonRpgBundle:Reward')->getRewardByIdAndUserIdAndIsAwardedAndIsReceivedV1($id, $this->user_id, $is_awarded, $is_received);

        if (!($reward)) {
            $message = "EventHorizonRpgBundle:Reward:receive id=".$id." user_id=".$this->user_id." is_awarded=".$is_awarded." is_received=".$is_received;
            EventHorizonRpgBundle::addNotice($message, $this->get('event_horizon_log'), $this->get('request'));

            throw $this->createNotFoundException('Unable to find Reward entity.');
        }

        $this->em->getRepository('EventHorizonRpgBundle:Reward')->receiveReward($reward, $this->user);

        $this->get('session')->setFlash('info', $this->get('translator')->trans('Nagroda została oznaczona jako odebrana'));

        return $this->redirect($this->generateUrl('reward'));
    }

    public function showAction($id)
    {
        $this->common();
        $reward = $this->em->getRepository('EventHorizonRpgBundle:Reward')->getRewardByIdAndUserIdV1($id, $this->user_id);

        if (!($reward)) {
            $message = "EventHorizonRpgBundle:Reward:show id=".$id." user_id=".$this->user_id;
            EventHorizonRpgBundle::addNotice($message, $this->get('event_horizon_log'), $this->get('request'));

            throw $this->createNotFoundException('Unable to find Reward entity.');
        }

        return $this->render('EventHorizonRpgBundle:Reward:RewardShow.html.twig', array(
            'is_awarded' => 0,
            'reward'     => $reward,
            'setup'      => $this->setup,
        ));
    }

    public function showAwardedAction($id)
    {
        $this->common();
        $is_awarded = 1;

        $reward = $this->em->getRepository('EventHorizonRpgBundle:Reward')->getRewardByIdAndUserIdAndIsAwardedV1($id, $this->user_id, $is_awarded);

        if (!($reward)) {
            $message = "EventHorizonRpgBundle:Reward:showAwarded id=".$id." user_id=".$this->user_id." is_awarded=".$is_awarded;
            EventHorizonRpgBundle::addNotice($message, $this->get('event_horizon_log'), $this->get('request'));

            throw $this->createNotFoundException('Unable to find Reward entity.');
        }

        return $this->render('EventHorizonRpgBundle:Reward:RewardShow.html.twig', array(
            'is_awarded' => $is_awarded,
            'reward'     => $reward,
            'setup'      => $this->setup,
        ));
    }
}

src/EventHorizon/RpgBundle/Resources/views/Reward/Edit.html.twig
{% extends 'EventHorizonRpgBundle::layout.html.twig' %}

{% block title %}
    {{ setup.gameName }} - {% filter lower %}{% trans %}Edycja nagrody{% endtrans %}{% endfilter %}
{% endblock %}

{% block breadcrumb %}
    <li><span class="divider">/</span> <a href="{{ path('character_show') }}">{% trans %}Postać{% endtrans %}</a></li>
    <li><span class="divider">/</span> <a href="{{ path('reward') }}">{% trans %}Nagrody{% endtrans %}</a></li>
    <li><span class="divider">/</span> <a href="{{ path('reward_edit', { 'id': reward.id }) }}">{% trans %}Edycja nagrody{% endtrans %}</a></li>
{% endblock %}

{% block content %}
    {% include 'EventHorizonRpgBundle:Reward:Form.html.twig' with { 'display_mode': 'edit' } %}
{% endblock %}

src/EventHorizon/RpgBundle/Resources/views/Reward/Form.html.twig
<div class="span8 offset2 well">
    {% if display_mode == 'new' %}
        <a class="btn btn-info btn-small vertical_align_top" data-content="{% trans %}W tym oknie można dodać nową nagrodę.<br /><br />Za wypełnienie szeregu zadań, użytkownik wyznacza sobie nagrodę, którą sobie zafunduje po ich ukończeniu. Nagroda pełni funkcję mobilizującą.{% endtrans %}" data-original-title="{% trans %}Nowa nagroda{% endtrans %}" data-trigger="hover" href="#" rel="popover"><i class="icon-question-sign icon-white"></i></a>
        <div class="page-header">
            <h3>{% trans %}Nowa nagroda{% endtrans %}</h3>
        </div>
        <form action="{{ path('reward_create') }}" class="form-horizontal" method="post" {{ form_enctype(form) }}>
    {% elseif display_mode == 'edit' %}
        <a class="btn btn-info btn-small vertical_align_top" data-content="{% trans %}W tym oknie można edytować opis nagrody.<br /><br />Za wypełnienie szeregu zadań, użytkownik wyznacza sobie nagrodę, którą sobie zafunduje po ich ukończeniu. Nagroda pełni funkcję mobilizującą.{% endtrans %}" data-original-title="{% trans %}Edycja nagrody{% endtrans %}" data-trigger="hover" href="#" rel="popover"><i class="icon-question-sign icon-white"></i></a>
        <div class="page-header">
            <h3>{% trans %}Edycja nagrody{% endtrans %}</h3>
        </div>
        <form action="{{ path('reward_update', { 'id': reward.id }) }}" class="form-horizontal" method="post" {{ form_enctype(form) }}>
    {% endif %}
        {{ form_errors(form) }}
        <fieldset>
            <div class="control-group">
                {{ form_errors(form.title) }}
                {{ form_label(form.title, null, { 'label_attr': {'class': 'control-label'} }) }}
                <div class="controls">
                    {{ form_widget(form.title, { 'attr': {'class': 'span5'} }) }}
                </div>
            </div>
            <div class="control-group">
                {{ form_errors(form.content) }}
                {{ form_label(form.content, null, { 'label_attr': {'class': 'control-label'} }) }}
                <div class="controls">
                    {{ form_widget(form.content, { 'attr': {'class': 'span5'} }) }}
                </div>
            </div>
            <div class="control-group">
                {{ form_errors(form.photo_file) }}
                {{ form_label(form.photo_file, null, { 'label_attr': {'class': 'control-label'} }) }}
                <div class="controls">
                    {{ form_widget(form.photo_file, { 'attr': {'class': 'span5'} }) }}
                </div>
            </div>
            <div class="accordion" id="accordion">
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                            {% trans %}Więcej{% endtrans %} <i class="icon-chevron-down"></i>
                        </a>
                    </div>
                    <div id="collapseOne" class="accordion-body collapse">
                        <div class="accordion-inner">
                            <div class="control-group">
                                {{ form_errors(form.is_visible) }}
                                {{ form_label(form.is_visible, null, { 'label_attr': {'class': 'control-label'} }) }}
                                <div class="controls">
                                    {{ form_widget(form.is_visible, { 'attr': {'class': 'span5'} }) }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {{ form_rest(form) }}
            <div class="form-actions">
                <button class="btn btn-primary" type="submit">{% trans %}Zapisz{% endtrans %}</button>
                <a class="btn" href="{{ path('reward') }}">{% trans %}Anuluj{% endtrans %}</a>
            </div>
        </fieldset>
    </form>
</div>

src/EventHorizon/RpgBundle/Resources/views/Reward/New.html.twig
{% extends 'EventHorizonRpgBundle::layout.html.twig' %}

{% block title %}
    {{ setup.gameName }} - {% filter lower %}{% trans %}Nowa nagroda{% endtrans %}{% endfilter %}
{% endblock %}

{% block breadcrumb %}
    <li><span class="divider">/</span> <a href="{{ path('character_show') }}">{% trans %}Postać{% endtrans %}</a></li>
    <li><span class="divider">/</span> <a href="{{ path('reward') }}">{% trans %}Nagrody{% endtrans %}</a></li>
    <li><span class="divider">/</span> <a href="{{ path('reward_new') }}">{% trans %}Nowa nagroda{% endtrans %}</a></li>
{% endblock %}

{% block content %}
    {% include 'EventHorizonRpgBundle:Reward:Form.html.twig' with { 'display_mode': 'new' } %}
{% endblock %}

src/EventHorizon/RpgBundle/Resources/views/Reward/Show.html.twig
{% if display_mode == 'show' %}
    <div class="span8 offset2 well">
        <a class="btn btn-info btn-small vertical_align_top" data-content="{% trans %}W tym oknie wyświetlana jest nagroda użytkownika.<br /><br />Za wypełnienie szeregu zadań, użytkownik wyznacza sobie nagrodę, którą sobie zafunduje po ich ukończeniu. Nagroda pełni funkcję mobilizującą.{% endtrans %}" data-original-title="{% trans %}Nagroda{% endtrans %}" data-trigger="hover" href="#" rel="popover"><i class="icon-question-sign icon-white"></i></a>
        <br /><br />
        <div class="row">
            {% if access_mode == 'admin' %}
                {% if is_awarded %}
                    <div class="span7">
                        <div class="page-header">
                            <h3>{% trans %}Gratulacje - masz nowy poziom! Dzięki wytrwałej pracy i pokonywaniu wyzwań osiągasz kolejny poziom. Możesz teraz sobie zafundować wymarzoną nagrodę.{% endtrans %}</h3>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
{% endif %}
<div class="span7">
    {% if display_mode == 'list' %}
        <div class="page-header"></div>
    {% endif %}
    {% if reward.photo and reward.checkAbsolutePath %}
        <img alt="{% trans %}Fotka{% endtrans %}" class="float_left margin_bottom_1em margin_right_1em" src="{{ reward.getWebPath | apply_filter('reward_thumb') }}" />
    {% else %}
        <img alt="{% trans %}Fotka{% endtrans %}" class="float_left margin_bottom_1em margin_right_1em" src="{{ asset('bundles/eventhorizonrpg/img/gift.png') }}" />
    {% endif %}
    {% if display_mode == 'list' %}
        {% if access_mode == 'admin' %}
            <h3><a href="{{ path('reward_show', { 'id': reward.id }) }}">{{ reward.title }}</a></h3>
        {% elseif access_mode == 'visitor' %}
            <h3><a href="{{ path('show_reward', { 'reward_id': reward.id, 'user_id': user_id }) }}">{{ reward.title }}</a></h3>
        {% endif %}
    {% elseif display_mode == 'show' %}
        <div class="page-header">
            <h3>{{ reward.title }}</h3>
        </div>
    {% endif %}
    <p>{{ reward.content }}</p>
    <h6 class="muted text_transform_uppercase">{% trans %}Poziom{% endtrans %}: {{ reward.level }}</h6>
    <div class="btn-toolbar">
        <div class="btn-group vertical_align_top">
            {% if reward.isAwarded == 0 %}
                <span class="label label-info l1-label"><i class="icon-road icon-white"></i> {% trans %}Do zdobycia{% endtrans %}</span>
            {% elseif reward.isAwarded == 1 %}
                <span class="label label-success l1-label"><i class="icon-thumbs-up icon-white"></i> {% trans %}Zdobyta{% endtrans %}</span>
            {% endif %}
        </div>
        {% if access_mode == 'admin' %}
            {% if reward.isAwarded == 0 %}
                <div class="btn-group">
                    <a class="btn btn-success btn-mini" href="{{ path('reward_edit', { 'id': reward.id }) }}"><i class="icon-edit icon-white vertical_align_middle"></i> {% trans %}Edycja nagrody{% endtrans %}</a>
                </div>
            {% elseif reward.isAwarded == 1 and reward.isReceived == 0 %}
                <div class="btn-group">
                    <a class="btn btn-warning btn-mini" href="{{ path('reward_receive', { 'id': reward.id }) }}"><i class="icon-gift icon-white vertical_align_middle"></i> {% trans %}Odebrana{% endtrans %}</a>
                </div>
            {% endif %}
        {% endif %}
        {% if display_mode == 'show' %}
            {% if access_mode == 'admin' %}
                {% if is_awarded %}
                    <div class="btn-group">
                        <a class="btn btn-mini btn-primary" href="{{ path('reward_new') }}"><i class="icon-gift icon-white vertical_align_middle"></i> {% trans %}Nowa nagroda{% endtrans %}</a>
                    </div>
                {% endif %}
                <div class="btn-group">
                    <a class="btn btn-mini" href="{{ path('reward') }}"><i class="icon-arrow-left vertical_align_middle"></i> {% trans %}Powrót{% endtrans %}</a>
                </div>
            {% elseif access_mode == 'visitor' %}
                <div class="btn-group">
                    <a class="btn btn-mini" href="{{ path('show_rewards', { 'user_id': user_id }) }}"><i class="icon-arrow-left vertical_align_middle"></i> {% trans %}Powrót{% endtrans %}</a>
                </div>
            {% endif %}
        {% endif %}
    </div>
</div>
{% if display_mode == 'show' %}
        </div>
    </div>
{% endif %}