src/EventHorizon/RpgBundle/Entity/User.php
<?php

namespace EventHorizon\RpgBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Entity\User as BaseUser;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * EventHorizon\RpgBundle\Entity\User
 *
 * @ORM\Table(
 *   name="rpg_user",
 *   indexes={
 *     @ORM\Index(name="iser_main_01_index", columns={"id", "username", "username_canonical", "email", "email_canonical", "enabled", "last_login", "locked", "expired", "expires_at", "password_requested_at", "created_at", "updated_at"})},
 *   uniqueConstraints={@ORM\UniqueConstraint(columns={"email_canonical"}), @ORM\UniqueConstraint(columns={"username_canonical"})})
 * @ORM\Entity(repositoryClass="EventHorizon\RpgBundle\Repository\UserRepository")
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\OneToOne(targetEntity="EventHorizon\RpgBundle\Entity\Account", mappedBy="user")
     */
    protected $account;

    /**
     * @ORM\OneToOne(targetEntity="EventHorizon\RpgBundle\Entity\Character", mappedBy="user")
     */
    protected $character;

    /**
     * @ORM\OneToMany(targetEntity="EventHorizon\RpgBundle\Entity\Journal", mappedBy="user")
     */
    protected $journal;

    /**
     * @ORM\OneToMany(targetEntity="EventHorizon\RpgBundle\Entity\Quest", mappedBy="user")
     */
    protected $quest;

    /**
     * @ORM\OneToMany(targetEntity="EventHorizon\RpgBundle\Entity\Reward", mappedBy="user")
     */
    protected $reward;

    /**
     * @var string $facebook_id
     *
     * @ORM\Column(name="facebook_id", nullable=true, type="string")
     */
    protected $facebook_id;

    /**
     * @var datetime $created_at
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $created_at;

    /**
     * @var datetime $updated_at
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        parent::__construct();

        $this->journal = new ArrayCollection();
        $this->quest = new ArrayCollection();
        $this->reward = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get account
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Get character
     */
    public function getCharacter()
    {
        return $this->character;
    }

    /**
     * Get created_at
     *
     * @return datetime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set created_at
     *
     * @param datetime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;
    }

    /**
     * Get updated_at
     *
     * @return datetime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Set updated_at
     *
     * @param datetime $updatedAt
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;
    }

    public function serialize()
    {
        return serialize(array($this->facebook_id, parent::serialize()));
    }

    public function unserialize($data)
    {
        list($this->facebook_id, $parentData) = unserialize($data);
        parent::unserialize($parentData);
    }

    /**
     * @param string $facebook_id
     *
     * @return void
     */
    public function setFacebookId($facebook_id = null)
    {
        $this->facebook_id = $facebook_id;
        if ($this->username=="") {
            $this->setUsername($facebook_id);
        }
        $this->salt = '';
    }

    /**
     * @return string
     */
    public function getFacebookId()
    {
        return $this->facebook_id;
    }

    /**
     * @param Array
     */
    public function setFBData($fbdata)
    {
        if (isset($fbdata['id'])) {
            $this->setFacebookId($fbdata['id']);
            //$this->addRole('ROLE_FACEBOOK');
            $this->setRoles(array('ROLE_PLAYER', 'ROLE_USER'));
        }
        if (isset($fbdata['email'])) {
            $this->setEmail($fbdata['email']);
        }
    }
}

src/EventHorizon/RpgBundle/Form/QuestType.php
<?php

namespace EventHorizon\RpgBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Validator\Constraints\MaxLength;
use Symfony\Component\Validator\Constraints\NotBlank;
use EventHorizon\RpgBundle\Form\Type\AttributeRewardType;
use EventHorizon\RpgBundle\Form\Type\BooleanType;
use EventHorizon\RpgBundle\Form\Type\QuestTypeType;
use EventHorizon\RpgBundle\Form\Type\SkillRewardType;

class QuestType extends AbstractType
{
    private $options = array();

    public function __construct(array $options)
    {
        $this->options = $options;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('attribute_reward', new AttributeRewardType(array('locale' => $this->options['locale'])), array(
                'constraints' => array(new NotBlank())
            ))
            ->add('content', 'textarea', array(
                'constraints' => array(
                    new MaxLength(16384),
                    new NotBlank(),
                )
            ))
            ->add('skill_reward', new SkillRewardType(array('locale' => $this->options['locale'])), array(
                'constraints' => array(new NotBlank())
            ))
            ->add('title', 'text', array(
                'constraints' => array(
                    new MaxLength(250),
                    new NotBlank(),
                )
            ))
            ->add('type', new QuestTypeType(array('locale' => $this->options['locale'])), array(
                'constraints' => array(new NotBlank())
            ))
        ;

        if (isset($this->options['journal'])) {
            $builder->add('is_visible', new BooleanType(), array(
                    'data' => $this->options['journal']->getIsVisible(),
                    'property_path' => false,
                ))
            ;
        } elseif (isset($this->options['user'])) {
            $builder->add('is_visible', new BooleanType(), array(
                    'data' => $this->options['user']->getAccount()->getDefaultJournalIsVisible(),
                    'property_path' => false,
                ))
            ;
        } else {
            $builder->add('is_visible', new BooleanType(), array(
                    'property_path' => false,
                ))
            ;
        }

        if (isset($this->options['journal'])) {
            $builder->add('publish_on_facebook', new BooleanType(), array(
                    'data' => $this->options['journal']->getPublishOnFacebook(),
                    'property_path' => false,
                ))
            ;
        } elseif (isset($this->options['user'])) {
            $builder->add('publish_on_facebook', new BooleanType(), array(
                    'data' => $this->options['user']->getAccount()->getDefaultJournalPublishOnFacebook(),
                    'property_path' => false,
                ))
            ;
        } else {
            $builder->add('publish_on_facebook', new BooleanType(), array(
                    'property_path' => false,
                ))
            ;
        }
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'EventHorizon\RpgBundle\Entity\Quest'
        ));
    }

    public function getName()
    {
        return 'eventhorizon_rpgbundle_questtype';
    }
}

src/EventHorizon/RpgBundle/Controller/QuestController.php
<?php

namespace EventHorizon\RpgBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use EventHorizon\RpgBundle\EventHorizonRpgBundle;
use EventHorizon\RpgBundle\Entity\Quest;
use EventHorizon\RpgBundle\Form\QuestType;

class QuestController extends Controller
{
    public function common()
    {
        $this->em = $this->getDoctrine()->getManager();
        $this->setup = $this->em->getRepository('EventHorizonRpgBundle:Setup')->getSetup();
        $this->user = $this->container->get('security.context')->getToken()->getUser();
        $this->user_id = $this->user->getId();
        $this->request = $this->getRequest();
        $this->request->setLocale($this->get('session')->get('_locale'));
        $this->locale = $this->request->getLocale();
        $this->request->getSession()->set('referrer', $this->request->getRequestUri());
    }

    public function NewCommon($journal_id)
    {
        $this->common();

        if ($journal_id) {
            $this->journal = $this->em->getRepository('EventHorizonRpgBundle:Journal')->getJournalByIdAndUserIdV1($journal_id, $this->user_id);

            if (!($this->journal)) {
                $message = "EventHorizonRpgBundle:Quest:new id=".$journal_id." user_id=".$this->user_id;
                EventHorizonRpgBundle::addNotice($message, $this->get('event_horizon_log'), $this->get('request'));

                throw $this->createNotFoundException('Unable to find Journal entity.');
            }
        } else {
            $this->journal = null;
        }

        $this->character = $this->em->getRepository('EventHorizonRpgBundle:Character')->getCharacterByUserIdV2($this->user_id);
        $this->level = ($this->character->getLevel() + 1);
        $this->rewardExists = $this->em->getRepository('EventHorizonRpgBundle:Reward')->getRewardsByUserIdAndLevelV1($this->user_id, $this->level);

        $this->quest = new Quest();
        $this->form = $this->createForm(new QuestType(array('locale' => $this->locale, 'user' => $this->user)), $this->quest);
    }

    public function newAction($journal_id)
    {
        $this->NewCommon($journal_id);

        if (!($this->rewardExists)) {
            return $this->redirect($this->generateUrl('reward_new'));
        }

        return $this->render('EventHorizonRpgBundle:Quest:New.html.twig', array(
            'form'       => $this->form->createView(),
            'journal_id' => $journal_id,
            'quest'      => $this->quest,
            'setup'      => $this->setup,
            'user'       => $this->user,
        ));
    }

    public function createAction($journal_id)
    {
        $this->NewCommon($journal_id);

        $this->form->bind($this->request);

        if ($this->form->isValid()) {
            $questType = $this->request->request->get('eventhorizon_rpgbundle_questtype');
            $is_visible = $questType['is_visible'];
            $publish_on_facebook = $questType['publish_on_facebook'];
            $this->journal = $this->em->getRepository('EventHorizonRpgBundle:Quest')->saveNewQuest($this->journal, $this->quest, $this->user, $is_visible, $publish_on_facebook);

            $this->publishOnFacebook($is_visible, $publish_on_facebook);

            return $this->redirect($this->generateUrl('journal', array('mode' => 'todo')));
        }

        if (!($this->rewardExists)) {
            return $this->redirect($this->generateUrl('reward_new'));
        }

        return $this->render('EventHorizonRpgBundle:Quest:New.html.twig', array(
            'form'       => $this->form->createView(),
            'journal_id' => $journal_id,
            'quest'      => $this->quest,
            'setup'      => $this->setup,
            'user'       => $this->user,
        ));
    }

    public function EditCommon($id)
    {
        $this->common();
        $this->is_group_quest = 0;
        $this->quest = $this->em->getRepository('EventHorizonRpgBundle:Quest')->getQuestByIdAndUserIdAndIsGroupQuestV1($id, $this->user_id, $this->is_group_quest);

        if (!($this->quest)) {
            $message = "EventHorizonRpgBundle:Quest:EditCommon id=".$id." user_id=".$this->user_id." is_group_quest=".$this->is_group_quest;
            EventHorizonRpgBundle::addNotice($message, $this->get('event_horizon_log'), $this->get('request'));

            throw $this->createNotFoundException('Unable to find Quest entity.');
        }

        $this->journal = $this->em->getRepository('EventHorizonRpgBundle:Journal')->getJournalByQuestIdAndUserIdV1($id, $this->user_id);

        if (!($this->journal)) {
            $message = "EventHorizonRpgBundle:Quest:EditCommon quest_id=".$id." user_id=".$this->user_id;
            EventHorizonRpgBundle::addNotice($message, $this->get('event_horizon_log'), $this->get('request'));

            throw $this->createNotFoundException('Unable to find Journal entity.');
        }

        $this->form = $this->createForm(new QuestType(array('journal' => $this->journal, 'locale' => $this->locale)), $this->quest);
    }

    public function editAction($id)
    {
        $this->EditCommon($id);

        return $this->render('EventHorizonRpgBundle:Quest:Edit.html.twig', array(
            'form'  => $this->form->createView(),
            'quest' => $this->quest,
            'setup' => $this->setup,
            'user'  => $this->user,
        ));
    }

    public function updateAction($id)
    {
        $this->EditCommon($id);

        $this->form->bind($this->request);

        if ($this->form->isValid()) {
            $questType = $this->request->request->get('eventhorizon_rpgbundle_questtype');
            $is_visible = $questType['is_visible'];
            $publish_on_facebook = $questType['publish_on_facebook'];
            $this->em->getRepository('EventHorizonRpgBundle:Quest')->saveEditQuest($this->journal, $this->quest, $this->user, $is_visible, $publish_on_facebook);

            $this->publishOnFacebook($is_visible, $publish_on_facebook);

            return $this->redirect($this->generateUrl('journal', array('mode' => 'todo')));
        }

        return $this->render('EventHorizonRpgBundle:Quest:Edit.html.twig', array(
            'form'  => $this->form->createView(),
            'quest' => $this->quest,
            'setup' => $this->setup,
            'user'  => $this->user,
        ));
    }

    public function publishOnFacebook($is_visible, $publish_on_facebook)
    {
        if (($is_visible) and ($publish_on_facebook) and ($this->user->getFacebookId()) and ($this->user->getCharacter()->getIsVisible())) {
            $facebookSdk = $this->get("armetiz.facebook.rpg");
            $accessToken = $facebookSdk->getAccessToken();
            $facebookSdk->setAccessToken($accessToken);
            $link = $this->generateUrl('show_journal', array('journal_id' => $this->journal->getId(), 'user_id' => $this->user_id), true);
            $messge = $this->user->getCharacter()->getName()." ".$this->get('translator')->trans('podejmuje nowe wyzwanie');

            try {
                $facebookSdk->api('/me/feed', 'POST', array(
                    'link' => $link,
                    'message' => $messge
                ));
            } catch (\Exception $e) {
                $this->get('session')->setFlash('error', $this->get('translator')->trans('Brak uprawnień do publikacji na Facebooku'));
            }
        }
    }
}

src/EventHorizon/RpgBundle/Resources/views/Quest/Edit.html.twig
{% extends 'EventHorizonRpgBundle::layout.html.twig' %}

{% block title %}
    {{ setup.gameName }} - {% filter lower %}{% trans %}Edycja zadania{% endtrans %}{% endfilter %}
{% endblock %}

{% block breadcrumb %}
    <li><span class="divider">/</span> <a href="{{ path('journal', { 'mode': 'todo' }) }}">{% trans %}Zadania{% endtrans %} - {% filter lower %}{% trans %}Do wykonania{% endtrans %}{% endfilter %}</a></li>
    <li><span class="divider">/</span> <a href="{{ path('quest_edit', { 'id': quest.id }) }}">{% trans %}Edycja zadania{% endtrans %}</a></li>
{% endblock %}

{% block content %}
    {% include 'EventHorizonRpgBundle:Quest:Form.html.twig' with { 'display_mode': 'edit' } %}
{% endblock %}

src/EventHorizon/RpgBundle/Resources/views/Quest/Form.html.twig
<div class="span8 offset2 well">
    {% if display_mode == 'new' %}
        <a class="btn btn-info btn-small vertical_align_top" data-content="{% trans %}W tym oknie można dodać nowe zadanie.<br /><br />Użytkownik wybiera cechę oraz współczynnik postaci, które wzrosną po wykonaniu tego zadania.<br /><br />Użytkownik wyznacza sobie kolejne cele (zadania). Realizując je zmienia i kształtuje swoje życie.{% endtrans %}" data-original-title="{% trans %}Nowe zadanie{% endtrans %}" data-trigger="hover" href="#" rel="popover"><i class="icon-question-sign icon-white"></i></a>
        <div class="page-header">
            <h3>{% trans %}Nowe zadanie{% endtrans %}</h3>
        </div>
        <form action="{{ path('quest_create', { 'journal_id': journal_id }) }}" class="form-horizontal" method="post" {{ form_enctype(form) }}>
    {% elseif display_mode == 'edit' %}
        <a class="btn btn-info btn-small vertical_align_top" data-content="{% trans %}W tym oknie można edytować opis zadania.<br /><br />Użytkownik wybiera cechę oraz współczynnik postaci, które wzrosną po wykonaniu tego zadania.<br /><br />Użytkownik wyznacza sobie kolejne cele (zadania). Realizując je zmienia i kształtuje swoje życie.{% endtrans %}" data-original-title="{% trans %}Edycja zadania{% endtrans %}" data-trigger="hover" href="#" rel="popover"><i class="icon-question-sign icon-white"></i></a>
        <div class="page-header">
            <h3>{% trans %}Edycja zadania{% endtrans %}</h3>
        </div>
        <form action="{{ path('quest_update', { 'id': quest.id }) }}" class="form-horizontal" method="post" {{ form_enctype(form) }}>
    {% endif %}
        {{ form_errors(form) }}
        <fieldset>
            <div class="control-group">
                {{ form_errors(form.title) }}
                {{ form_label(form.title, null, { 'label_attr': {'class': 'control-label'} }) }}
                <div class="controls">
                    {{ form_widget(form.title, { 'attr': {'class': 'span5'} }) }}
                </div>
            </div>
            <div class="control-group">
                {{ form_errors(form.content) }}
                {{ form_label(form.content, null, { 'label_attr': {'class': 'control-label'} }) }}
                <div class="controls">
                    {{ form_widget(form.content, { 'attr': {'class': 'span5'} }) }}
                </div>
            </div>
            <div class="control-group">
                {{ form_errors(form.attribute_reward) }}
                {{ form_label(form.attribute_reward, null, { 'label_attr': {'class': 'control-label'} }) }}
                <div class="controls">
                    {{ form_widget(form.attribute_reward, { 'attr': {'class': 'span5'} }) }}
                </div>
            </div>
            <div class="control-group">
                {{ form_errors(form.skill_reward) }}
                {{ form_label(form.skill_reward, null, { 'label_attr': {'class': 'control-label'} }) }}
                <div class="controls">
                    {{ form_widget(form.skill_reward, { 'attr': {'class': 'span5'} }) }}
                </div>
            </div>
            <div class="accordion" id="accordion">
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                            {% trans %}Więcej{% endtrans %} <i class="icon-chevron-down"></i>
                        </a>
                    </div>
                    <div id="collapseOne" class="accordion-body collapse">
                        <div class="accordion-inner">
                            <div class="control-group">
                                {{ form_errors(form.is_visible) }}
                                {{ form_label(form.is_visible, null, { 'label_attr': {'class': 'control-label'} }) }}
                                <div class="controls">
                                    {{ form_widget(form.is_visible, { 'attr': {'class': 'span5'} }) }}
                                </div>
                            </div>
                            <div class="{% if user.facebookId is not defined or user.facebookId is null  %}display_none{% endif %}">
                                <div class="control-group" id="eventhorizon_rpgbundle_questtype_publish_on_facebook_select">
                                    {{ form_errors(form.publish_on_facebook) }}
                                    {{ form_label(form.publish_on_facebook, null, { 'label_attr': {'class': 'control-label'} }) }}
                                    <div class="controls">
                                        {{ form_widget(form.publish_on_facebook, { 'attr': {'class': 'span5'} }) }}
                                    </div>
                                </div>
                            </div>
                            <div class="control-group">
                                {{ form_errors(form.type) }}
                                {{ form_label(form.type, null, { 'label_attr': {'class': 'control-label'} }) }}
                                <div class="controls">
                                    {{ form_widget(form.type, { 'attr': {'class': 'span5'} }) }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {{ form_rest(form) }}
            <div class="form-actions">
                <button class="btn btn-primary" type="submit">{% trans %}Zapisz{% endtrans %}</button>
                <a class="btn" href="{{ path('journal', { 'mode': 'todo' }) }}">{% trans %}Anuluj{% endtrans %}</a>
            </div>
        </fieldset>
    </form>
</div>

src/EventHorizon/RpgBundle/Resources/views/Quest/New.html.twig
{% extends 'EventHorizonRpgBundle::layout.html.twig' %}

{% block title %}
    {{ setup.gameName }} - {% filter lower %}{% trans %}Nowe zadanie{% endtrans %}{% endfilter %}
{% endblock %}

{% block breadcrumb %}
    <li><span class="divider">/</span> <a href="{{ path('journal', { 'mode': 'todo' }) }}">{% trans %}Zadania{% endtrans %} - {% filter lower %}{% trans %}Do wykonania{% endtrans %}{% endfilter %}</a></li>
    <li><span class="divider">/</span> <a href="{{ path('quest_new') }}">{% trans %}Nowe zadanie{% endtrans %}</a></li>
{% endblock %}

{% block content %}
    {% include 'EventHorizonRpgBundle:Quest:Form.html.twig' with { 'display_mode': 'new' } %}
{% endblock %}